-- Chave Verde — avaliações do site (depoimentos com estrelas de 1 a 5)
-- Rode uma vez no Supabase: Dashboard -> SQL Editor -> New query -> cole tudo -> Run.
-- Seguro rodar de novo (idempotente).

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  nome text,
  nota int not null,
  comentario text,
  aprovada boolean not null default false,
  criado_em timestamptz not null default now()
);

-- limites de tamanho / nota válida (valem pra todo mundo)
alter table public.avaliacoes drop constraint if exists avaliacoes_nota_valida;
alter table public.avaliacoes add constraint avaliacoes_nota_valida check (nota between 1 and 5);
alter table public.avaliacoes drop constraint if exists avaliacoes_comentario_tam;
alter table public.avaliacoes add constraint avaliacoes_comentario_tam check (comentario is null or char_length(comentario) <= 500);
alter table public.avaliacoes drop constraint if exists avaliacoes_nome_tam;
alter table public.avaliacoes add constraint avaliacoes_nome_tam check (nome is null or char_length(nome) <= 60);

alter table public.avaliacoes enable row level security;

-- O público só enxerga avaliações aprovadas
drop policy if exists "publico ve avaliacoes aprovadas" on public.avaliacoes;
create policy "publico ve avaliacoes aprovadas"
on public.avaliacoes for select
using ( aprovada = true );

-- Admin enxerga todas (inclusive as pendentes)
drop policy if exists "admin ve todas avaliacoes" on public.avaliacoes;
create policy "admin ve todas avaliacoes"
on public.avaliacoes for select
using ( auth.uid() in (select user_id from public.admins) );

-- Qualquer visitante pode enviar (cai como pendente)
drop policy if exists "qualquer um avalia" on public.avaliacoes;
create policy "qualquer um avalia"
on public.avaliacoes for insert
with check ( true );

-- Só admin aprova / esconde
drop policy if exists "admin edita avaliacoes" on public.avaliacoes;
create policy "admin edita avaliacoes"
on public.avaliacoes for update
using ( auth.uid() in (select user_id from public.admins) );

-- Só admin apaga
drop policy if exists "admin apaga avaliacoes" on public.avaliacoes;
create policy "admin apaga avaliacoes"
on public.avaliacoes for delete
using ( auth.uid() in (select user_id from public.admins) );

-- Trigger: no envio público força "pendente" e limita spam
create or replace function public.checar_avaliacao()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recentes int;
begin
  new.aprovada := false;         -- o cliente nunca decide se já está aprovada
  new.criado_em := now();
  -- teto anti-flood: 60 avaliações por hora no site todo
  select count(*) into recentes
  from public.avaliacoes
  where criado_em > now() - interval '1 hour';
  if recentes >= 60 then
    raise exception 'Muitas avaliações agora. Tente mais tarde.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_checar_avaliacao on public.avaliacoes;
create trigger trg_checar_avaliacao
before insert on public.avaliacoes
for each row execute function public.checar_avaliacao();
