-- Chave Verde — denúncias de anúncios suspeitos
-- Rode isso uma vez no Supabase: Dashboard → SQL Editor → New query → cole tudo → Run

create table if not exists public.denuncias (
  id bigint generated by default as identity primary key,
  anuncio_id bigint references public.quartos(id) on delete cascade,
  motivo text not null,
  criado_em timestamptz not null default now(),
  resolvida boolean not null default false
);

alter table public.denuncias enable row level security;

-- Qualquer visitante (mesmo sem login) pode denunciar
drop policy if exists "qualquer um pode denunciar" on public.denuncias;
create policy "qualquer um pode denunciar"
on public.denuncias for insert
with check ( true );

-- Só admin lê as denúncias
drop policy if exists "admin ve denuncias" on public.denuncias;
create policy "admin ve denuncias"
on public.denuncias for select
using ( auth.uid() in (select user_id from public.admins) );

-- Só admin marca como resolvida
drop policy if exists "admin resolve denuncias" on public.denuncias;
create policy "admin resolve denuncias"
on public.denuncias for update
using ( auth.uid() in (select user_id from public.admins) );
