-- Chave Verde — tabela de sugestões/feedback dos anunciantes pro time
-- Rode isso uma vez no Supabase: Dashboard → SQL Editor → New query → cole tudo → Run

create table if not exists public.feedback_mensagens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mensagem text not null,
  criado_em timestamptz not null default now(),
  lida boolean not null default false
);

alter table public.feedback_mensagens enable row level security;

drop policy if exists "usuarios enviam sua propria mensagem" on public.feedback_mensagens;
create policy "usuarios enviam sua propria mensagem"
on public.feedback_mensagens for insert
with check (auth.uid() = user_id);

drop policy if exists "usuarios veem suas proprias mensagens" on public.feedback_mensagens;
create policy "usuarios veem suas proprias mensagens"
on public.feedback_mensagens for select
using (auth.uid() = user_id);

drop policy if exists "admins veem todas as mensagens" on public.feedback_mensagens;
create policy "admins veem todas as mensagens"
on public.feedback_mensagens for select
using (auth.uid() in (select user_id from public.admins));

drop policy if exists "admins marcam mensagens como lidas" on public.feedback_mensagens;
create policy "admins marcam mensagens como lidas"
on public.feedback_mensagens for update
using (auth.uid() in (select user_id from public.admins));
